### ISSUE TITLE
M1 - Release

### ISSUE THREAD

**Issue by yago1994** [AppHatchery/GA-TB-Reference-Guide-Web#18]
# Goal
Prepare for M1 Release

## Tasks

- [x] Change toolbar positioning iOS and Android
- [x] Replace 'Saved' tab iOS and Android
- [x] UI Changes on the Home page iOS and Android
- [x] Update TB Coordinators list
- [x] Set minimum deployment targets iOS and Android
- [x] Verify Pendo SDK -> Update to 3.3.0 https://developers.pendo.io/agent-sdk-updates/

Release

- [x] Test iOS internal testing
- [x] Submit iOS to production
- [x] Test Pendo visitor Ids in Android (on Test account)
- [x] Make test bundle and upload to internal testing
- [x] Test on device from internal testing
- [x] Make production bundle
- [x] Submit to production directly

**Comment by MorganGreenleaf-Emory** [comment]
For submission to Android Play Store, I have the keystore and password if anyone needs it

**Comment by yago1994** [comment]
@Wiza-Munthali did the Pendo visitor ID get updated to July 24 like Android?

![Image](https://github.com/user-attachments/assets/b01e3b02-2880-42b1-9e87-eb8312a6881c)

**Comment by Wiza-Munthali** [comment]
I don't think I changed the ID, my apologies. Should we create a new build with the new ID?

**Comment by yago1994** [comment]
Production Build is Live v1.14.1
